name: collatz-conjecture
version: 1.2.0.2

dependencies:
  - base

library:
  exposed-modules: CollatzConjecture
  source-dirs: src
  dependencies:
    - mtl
tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - collatz-conjecture
      - hspec
