name: phone-number
version: 1.4.0.5

dependencies:
  - base

library:
  exposed-modules: Phone
  source-dirs: src
  dependencies:
    - regex-posix

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - phone-number
      - hspec
